app:
    resource: "@AppBundle/Controller/"
    type:     annotation
cars:
    type:     rest
    host:     rent-api.local
    resource: RentApiBundle\Controller\CarsController
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
